---
- hosts: all
  gather_facts: no

  vars:
    appname: bdbot2-test

  tasks:
  - name: Sync src folder
    synchronize: src='../app' dest='/{{appname}}'

  - name: Copy src to host
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: "../config/config_test.py", dest: "/{{appname}}/app/src/config.py" }

  - name: Delete old image
    docker_image:
      name: "{{appname}}-image"
      state: absent
      force_absent: yes

  - name: Build new image
    docker_image:
      build:
        path: /{{appname}}/app
      name: "{{appname}}-image"
      source: build

  - name: Run container
    docker_container:
      name: "{{appname}}"
      image: "{{appname}}-image"
      state: started
      recreate: yes
      restart_policy: on-failure
